### ISSUE TITLE
Unwanted behaviour of Glightbox

### ISSUE THREAD

**Issue by Seefahrer** [inspiredminds/contao-glightbox#1]
Hello Spooky,
first of all many thanks for this nice extension. On https://www.luetten-dieks-carlito.eu I replaced your no longer maintained „Lightcase“ extension with „Glightbox“. So far so good but I observed fllwg unwanted behaviour:

On my site I have a lot of single images with the option „Großansicht/Neues Fenster“ as well as many image galleries (Rocksolid).
When I open a gallery everything is fine, all images (and only the images belonging to that particular gallery) are being displayed in glightbox. As long as the option „loop: ‚true‘“ isn’t given the „Next“ arrow disappears when reaching the last images or vice versa the „Previous“ arrow.

BUT if I a click on one of the single images, glightbox opens and both arrows are shown and I can navigate thru **ALL images on the site including ALL gallery images**. That is actually unwanted. I think **only the particular image** on which I click for full view should be displayed.

I hope there is an easy to realize workaround?!

**Comment by fritzmg** [comment]
I was unable to reproduce the issue. Inserting multiple image or text content elements will not group them in a gallery.

The reason why this happens for you is because in your case the `data-lightbox` attribute is empty. You need to analyse why this is or make sure that the `data-lightbox` attribute always has a unique value, otherwise all images with an empty `data-lightbox` attribute will be grouped together.

**Comment by Seefahrer** [comment]
The images are inserted as standard Contao content element „Bild“ with the option „Großansicht/Neues Fenster“.
Do you have an idea how it happens that the `data-element` attrribute remains empty?

As far I can see in the browser analytic tools this seems to be a standard behaviour which didn’t lead to such issues e.g. in the former „lightcase“ extension.

**Comment by fritzmg** [comment]
`ContentImage` calls `Controller::addImageToTemplate` with `null` as the `$strLightboxId` variable (`ContentText` does the same):

https://github.com/contao/contao/blob/20cbb7fa7cd4714649d12de6239ccd0584cba773/core-bundle/src/Resources/contao/elements/ContentImage.php#L64

`Controller::addImageToTemplate` will then generate a lightbox ID:

https://github.com/contao/contao/blob/20cbb7fa7cd4714649d12de6239ccd0584cba773/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1783-L1787

The HTML output with the standard templates and standard content elements will then look like this for example:

```html
<a href="…" data-lightbox="c26a84">
```

**Comment by fritzmg** [comment]
Furthermore: your page has invalid HTML. The output of your text content element produces HTML like this:

```html
<img src="assets/images/9/carlo_2021-e347f4a5.png"< width="250" height="208" alt="" itemprop="image">
```

It looks like you are using custom templates with erroneous HTML.

**Comment by Seefahrer** [comment]
The HTML error has been solved (copy/paste mistake in a no longer needed `picture_default.html5` in the templates folder).

But do you have any clue about possible reasons why the lightbox id is not being generated for single images as intended?
For the images which are parts of a Rocksoild gallery valid IDs are being assigned ... a bit strange ...

**Comment by fritzmg** [comment]
I don't know, you'd have to debug the respective parts of the code.

**Comment by Seefahrer** [comment]
Fritz, I just checked the installed core files and I’m quite astonished to see that your above referenced code snippets in `ContentImage.php` and `Controller.php` are neither being part of `Contao 4.12.5` nor of `4.13-RC1`.

Modifying both files with your respective snippets/files does work in `Contao 4.12.5`. In 4.13-RC1 it leads to an unformatted frontend output.

**Comment by fritzmg** [comment]
If this is reproducible in a fresh Contao 4.12 or 4.13 installation (may be even with the default colorbox?), you should open a ticket here: https://github.com/contao/contao/issues/new?assignees=&labels=bug%2Cunconfirmed&template=1_Bug_report.yml

**Comment by Seefahrer** [comment]
Gonna check it ... But how to explain why the above referenced files are different from the distributed core files ...

**Comment by fritzmg** [comment]
I was able to reproduce it in Contao 4.12+. I will create a ticket there myself.

> But how to explain why the above referenced files are different from the distributed core files ...

The above links reference Contao 4.9. You did not specify the Contao version in your ticket.

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/issues/4029

**Comment by Seefahrer** [comment]
You are right ... thank you
